name: Otomatik Mekan Uretici ve Yükleyici

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu Klonla
      uses: actions/checkout@v3

    - name: Python Kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Kütüphaneleri Yükle
      run: |
        python -m pip install --upgrade pip
        pip install requests google-generativeai

    - name: Beyni Çalıştır (HTML'leri Üret)
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: python otomasyon.py

    - name: FTP ile Sınırsız Hostinge Yükle
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        local-dir: ./dist/
        server-dir: /public_html/
